users:
  email:
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    max_length: 255
  name:
    min_length: 5
    max_length: 50
  password:
    min_length: 6
    max_length: 32
    regex: !ruby/regexp '/[A-Z][a-z]\d/i'
remember_me: "1"
