users:
  paging:
    paging_number: 10
  email:
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    max_length: 255
  name:
    min_length: 5
    max_length: 50
  password:
    min_length: 6
    max_length: 32
    regex: !ruby/regexp '/[A-Z][a-z]\d/i'
  reset_sent_at:
    expired_time: 2
following:
  paging_number: 50
follower:
  paging_number: 50
  following:
    paging_number: 10
remember_me: "1"
facebook:
  scope: "email"
words:
  max_length: 60
  paging:
    page_nummber: 10
theme:
  paging: 'twitter-bootstrap-4'
courses:
  paging:
    page_number: 10
questions:
  paging:
    paging_number: 10
